name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        working-directory: App/buybc-app
        run: docker build . --file Dockerfile --tag buybc-app:$(date +%s)
      
  install_doctl:
    name: install Digital Ocean tools
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: digitalocean/action-doctl@v2
      - name: Install doctl
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  register:
    name: Register image on Digital Ocean
    runs-on: ubuntu-latest
    needs: [build, install_doctl]
    steps:
      - name: push image to Digital Ocean Registry
        run: cd .
