name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build, Push Image, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta
        
      - name: Build Docker Image
        working-directory: App/buybc-app
        run: docker build --file Dockerfile --tag registry.digitalocean.com/buybc/buybc-app:$(echo $GITHUB_SHA | head -c7) .
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/buybc/buybc-app:latest
